# Generated by Django 2.2.5 on 2020-01-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInput',
            fields=[
                ('priceid', models.AutoField(db_column='priceId', primary_key=True, serialize=False)),
                ('catactivematerial', models.FloatField(blank=True, db_column='catActiveMaterial', null=True)),
                ('catbinder', models.FloatField(blank=True, db_column='catBinder', null=True)),
                ('catconductor', models.FloatField(blank=True, db_column='catConductor', null=True)),
                ('anactivematerial', models.FloatField(blank=True, db_column='anActiveMaterial', null=True)),
                ('anbinder', models.FloatField(blank=True, db_column='anBinder', null=True)),
                ('anconductor', models.FloatField(blank=True, db_column='anConductor', null=True)),
                ('alfoil', models.FloatField(blank=True, db_column='alFoil', null=True)),
                ('cufoil', models.FloatField(blank=True, db_column='cuFoil', null=True)),
                ('can', models.FloatField(blank=True, null=True)),
                ('sep', models.FloatField(blank=True, null=True)),
                ('elyte', models.FloatField(blank=True, null=True)),
                ('cellmanufacturing', models.FloatField(blank=True, db_column='cellManufacturing', null=True)),
                ('packintegration', models.FloatField(blank=True, db_column='packIntegration', null=True)),
            ],
            options={
                'db_table': 'price_input',
            },
        ),
    ]
