# Generated by Django 2.2.5 on 2020-01-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20200101_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceinput',
            old_name='priceid',
            new_name='price_id',
        ),
        migrations.RemoveField(
            model_name='priceinput',
            name='alfoil',
        ),
        migrations.RemoveField(
            model_name='priceinput',
            name='anactivematerial',
        ),
        migrations.RemoveField(
            model_name='priceinput',
            name='anbinder',
        ),
        migrations.RemoveField(
            model_name='priceinput',
            name='anconductor',
        ),
        migrations.RemoveField(
            model_name='priceinput',
            name='catactivematerial',
        ),
        migrations.RemoveField(
            model_name='priceinput',
            name='catbinder',
        ),
        migrations.RemoveField(
            model_name='priceinput',
            name='catconductor',
        ),
        migrations.RemoveField(
            model_name='priceinput',
            name='cellmanufacturing',
        ),
        migrations.RemoveField(
            model_name='priceinput',
            name='cufoil',
        ),
        migrations.RemoveField(
            model_name='priceinput',
            name='packintegration',
        ),
        migrations.AddField(
            model_name='priceinput',
            name='al_foil',
            field=models.DecimalField(db_column='alFoil', decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceinput',
            name='an_active_material',
            field=models.DecimalField(db_column='anActiveMaterial', decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceinput',
            name='an_binder',
            field=models.DecimalField(db_column='anBinder', decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceinput',
            name='an_conductor',
            field=models.DecimalField(db_column='anConductor', decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceinput',
            name='cat_active_material',
            field=models.DecimalField(db_column='catActiveMaterial', decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceinput',
            name='cat_binder',
            field=models.DecimalField(db_column='catBinder', decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceinput',
            name='cat_conductor',
            field=models.DecimalField(db_column='catConductor', decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceinput',
            name='cell_manufacturing',
            field=models.DecimalField(db_column='cellManufacturing', decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceinput',
            name='cu_foil',
            field=models.DecimalField(db_column='cuFoil', decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceinput',
            name='pack_integration',
            field=models.DecimalField(db_column='packIntegration', decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='can',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='elyte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='sep',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
