# Generated by Django 2.2.5 on 2020-01-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_priceinput_price_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceinput',
            name='al_foil',
            field=models.FloatField(db_column='alFoil'),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='an_active_material',
            field=models.FloatField(db_column='anActiveMaterial'),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='an_binder',
            field=models.FloatField(db_column='anBinder'),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='an_conductor',
            field=models.FloatField(db_column='anConductor'),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='can',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='cat_active_material',
            field=models.FloatField(db_column='catActiveMaterial'),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='cat_binder',
            field=models.FloatField(db_column='catBinder'),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='cat_conductor',
            field=models.FloatField(db_column='catConductor'),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='cell_manufacturing',
            field=models.FloatField(db_column='cellManufacturing'),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='cu_foil',
            field=models.FloatField(db_column='cuFoil'),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='elyte',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='pack_integration',
            field=models.FloatField(db_column='packIntegration'),
        ),
        migrations.AlterField(
            model_name='priceinput',
            name='sep',
            field=models.FloatField(),
        ),
    ]
