# Generated by Django 2.2.5 on 2020-01-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellInput',
            fields=[
                ('cellid', models.AutoField(db_column='cellId', primary_key=True, serialize=False)),
                ('cellname', models.CharField(db_column='cellName', max_length=45, unique=True)),
                ('celltype', models.CharField(db_column='cellType', max_length=45)),
                ('npratio', models.FloatField(db_column='npRatio')),
                ('electrodelength', models.FloatField(db_column='electrodeLength')),
                ('electrodewidth', models.FloatField(db_column='electrodeWidth')),
                ('catformulaid', models.IntegerField(blank=True, db_column='catFormulaId', null=True)),
                ('catgravcapacity', models.FloatField(db_column='catGravCapacity')),
                ('cattotalloading', models.FloatField(db_column='catTotalLoading')),
                ('catactivefrac', models.FloatField(db_column='catActiveFrac')),
                ('catbinderfrac', models.FloatField(db_column='catBinderFrac')),
                ('catconductorfrac', models.FloatField(db_column='catConductorFrac')),
                ('angravcapacity', models.FloatField(db_column='anGravCapacity')),
                ('anactivefrac', models.FloatField(db_column='anActiveFrac')),
                ('anbinderfrac', models.FloatField(db_column='anBinderFrac')),
                ('anconductorfrac', models.FloatField(db_column='anConductorFrac')),
                ('alfoilthickness', models.FloatField(db_column='alFoilThickness')),
                ('cufoilthickness', models.FloatField(db_column='cuFoilThickness')),
                ('elyte', models.CharField(blank=True, max_length=45, null=True)),
                ('separatorname', models.CharField(blank=True, db_column='separatorName', max_length=45, null=True)),
                ('can', models.CharField(blank=True, max_length=45, null=True)),
                ('avgdischargevoltage', models.FloatField(db_column='avgDischargeVoltage')),
            ],
            options={
                'db_table': 'cell_input',
            },
        ),
    ]
