# Generated by Django 2.2.5 on 2020-01-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellinput',
            options={'managed': True},
        ),
    ]
