# Generated by Django 2.2.5 on 2020-01-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0004_auto_20200102_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellinput',
            name='cell_name',
            field=models.CharField(db_column='cellName', max_length=45),
        ),
    ]
