# Generated by Django 2.2.5 on 2020-01-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0005_auto_20200102_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellinput',
            name='cell_type',
            field=models.CharField(choices=[('18650', '18650'), ('2170', '2170')], db_column='cellType', default='18650', max_length=45),
        ),
    ]
