# Generated by Django 2.2.5 on 2020-01-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0006_auto_20200102_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellinput',
            name='al_foil_thickness',
            field=models.FloatField(db_column='alFoilThickness'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='an_active_frac',
            field=models.FloatField(db_column='anActiveFrac'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='an_binder_frac',
            field=models.FloatField(db_column='anBinderFrac'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='an_conductor_frac',
            field=models.FloatField(db_column='anConductorFrac'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='an_grav_capacity',
            field=models.FloatField(db_column='anGravCapacity'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='avg_discharge_voltage',
            field=models.FloatField(db_column='avgDischargeVoltage'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='cat_active_frac',
            field=models.FloatField(db_column='catActiveFrac'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='cat_binder_frac',
            field=models.FloatField(db_column='catBinderFrac'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='cat_conductor_frac',
            field=models.FloatField(db_column='catConductorFrac'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='cat_formula_id',
            field=models.IntegerField(db_column='catFormulaId', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='cat_grav_capacity',
            field=models.FloatField(db_column='catGravCapacity'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='cat_total_loading',
            field=models.FloatField(db_column='catTotalLoading'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='cu_foil_thickness',
            field=models.FloatField(db_column='cuFoilThickness'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='electrode_length',
            field=models.FloatField(db_column='electrodeLength'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='electrode_width',
            field=models.FloatField(db_column='electrodeWidth'),
        ),
        migrations.AlterField(
            model_name='cellinput',
            name='np_ratio',
            field=models.FloatField(db_column='npRatio'),
        ),
    ]
