# Generated by Django 2.2.5 on 2020-01-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0007_auto_20200105_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellinput',
            name='cell_name',
            field=models.CharField(db_column='cellName', max_length=45, unique=True),
        ),
    ]
